---

# -------------------- #
# --- Pre-required --- #
# -------------------- #
- hosts: localhost
  connection: local
  tasks:
  - name: Disable Swap
    command: swapoff -a
    
# -------------- #
# --- Docker --- #
# -------------- #
- hosts: localhost
  connection: local
  roles:
  - delete_docker     # Used to delete old instances
  - install_docker    # Install Docker Engine

# ------------------ #
# --- Kubernetes --- #
# ------------------ #
## - Set-up the cluster & master node
- hosts: localhost
  connection: local
  roles:
  - install_k8s
  - k8s_cluster
  - install_calico    # For the Network Interface

## - Untaint master node to have the single node cluster
- hosts: localhost
  connection: local
  tasks:
  - name: untaint master node
    command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
